### ISSUE TITLE
Windows 11 error

### ISSUE THREAD

**Issue by ryanto** [twofold-rsc/twofold#21]
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:249:11)
    at defaultLoad (node:internal/modules/esm/load:130:3)
    at ModuleLoader.load (node:internal/modules/esm/loader:553:13)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:434:56)
    at new ModuleJob (node:internal/modules/esm/module_job:71:27)
    at #createModuleJob (node:internal/modules/esm/loader:447:17)
    at ModuleLoader.getJobFromResolveResult (node:internal/modules/esm/loader:259:34)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:240:17)
    at async ModuleLoader.import (node:internal/modules/esm/loader:472:23) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
🏗️  Built app in 602.56ms [version: 95ff0c595632]
🚀 Server listening on http://0.0.0.0:3000/

Windows 11 Version 23H2 (0S Build 22631.4169)

_Originally posted by @WahyuIndG in https://github.com/twofold-rsc/twofold/issues/16#issuecomment-2363648894_

**Comment by ryanto** [comment]
Fixed in version `0.0.27`

**Comment by WahyuIndG** [comment]
hi @ryanto , glad to hear the latest update but unfortunately I still get an error with the following message when i try to `npm run dev`, I don't know where this error comes from, so is there anything I need to do ?

![image](https://github.com/user-attachments/assets/970271d3-4647-4586-a378-969615bb2ad6)


*note, i got this error one below when I first install the prooject `pnpm create twofold-app@latest` but I thought this was not related to the error above so i just continue with `npm run dev`
![image](https://github.com/user-attachments/assets/c075b90f-a36c-4e09-ab4b-327a08d51212)

**Comment by ryanto** [comment]
Right now twofold only supports pnpm, so you'll need to run `pnpm run dev`.

Also, it looks like you're trying to create a 2nd twofold app (second-try) inside of your first twofold app (react-server-component). I don't think that will work... my advice would be to start fresh.

Here's what I would do, delete the directories you created and start with:

```
pnpm create twofold-app@latest
```

Then cd into the directory it creates and run

```
pnpm run dev
```

Hopefull that works!

And I just wanted to thank you for reporting all these issues. It helps me fix all these bugs, so don't hesitate to report more issues if they come up!

**Comment by WahyuIndG** [comment]
oh, I missed it. Finally it's work thank you 🙂

**Comment by ryanto** [comment]
That's great to hear! Don't hesitate to reach out if you need help with anything RSC related
